# Generated by Django 4.0.1 on 2022-01-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_location', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
                ('user', models.ManyToManyField(to='users.User')),
            ],
            options={
                'db_table': 'suyo_locations',
            },
        ),
    ]
