# Generated by Django 4.0.1 on 2022-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='property',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
